added type hints to boxes.py
SmylerMC/litemapy pull request #44
Opened 2024-01-31 10:42 UTC by Phil-hacker

2024-02-02 11:18 UTC, Phil-hacker commented
i changed the constructor for DiscriminatingDictionary for better type hints
DiscriminatingDictionary should probably be refactored to allow for better type hints

2024-02-03 07:42 UTC, SmylerMC requested changes
Pretty good overall with a few problems:
- The binary OR syntax for types was added in Python 3.10. We need to support 3.9 so I think the only solution is to fallback to [`typing.Union`](https://docs.python.org/3/library/typing.html#typing.Union). This is preventing CI to pass.
- Formatting (I can fix that myself before merging if you prefer):
  - classes and function on the global scope need two blank lines prior to their declaration,
  - Methods need one blank line prior to their declaration,
  - `=` in keyword arguments need spaces on both sides when used with annotations
  - Comma should be followed by a blank.

2024-02-03 07:42 UTC, SmylerMC commented on litemapy/storage.py
> +    validator: Callable[[Any],tuple[bool, str]]
`validator` gets both the key and its value as parameters.

```suggestion
    validator: Callable[[Any, Any],tuple[bool, str]]
```

2024-02-03 07:42 UTC, SmylerMC commented on litemapy/storage.py
> +    def __init__(self, validator: Callable[[Any],tuple[bool, str]], *args, onadd: Callable[[Any,Any],None] | None = None,onremove: Callable[[Any,Any],None] | None = None, **options) -> None:
This line is way too long and has formatting problems

2024-02-03 07:42 UTC, SmylerMC commented on litemapy/storage.py
> +    def update(self, other: 'DiscriminatingDictionary') -> None:
This should accept vanilla dictionaries as well.

2024-02-03 07:42 UTC, SmylerMC commented on litemapy/boxes.py
> +def box_is_in_box(box1: tuple[tuple[int, int, int], tuple[int, int, int]], box2: tuple[tuple[int, int, int], tuple[int, int, int]]) -> bool:
Line too long.

2024-02-04 01:14 UTC, SmylerMC requested changes
Still has a few formatting problems, I taking care of it

2024-02-04 01:20 UTC, SmylerMC approved these changes
Looks all good now.

2024-02-04 01:22 UTC, SmylerMC commented
Merging, thank you @Phil-hacker !

2024-02-04 01:23 UTC, merged